In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
base_dfz = pd.read_csv("tel_churn1.csv")
base_dfz.shape

(7032, 52)

In [3]:
base_dfz

Unnamed: 0  SeniorCitizen  MonthlyCharges  TotalCharges  Churn  \
0              0              0           29.85         29.85      0   
1              1              0           56.95       1889.50      0   
2              2              0           53.85        108.15      1   
3              3              0           42.30       1840.75      0   
4              4              0           70.70        151.65      1   
...          ...            ...             ...           ...    ...   
7027        7038              0           84.80       1990.50      0   
7028        7039              0          103.20       7362.90      0   
7029        7040              0           29.60        346.45      0   
7030        7041              1           74.40        306.60      1   
7031        7042              0          105.65       6844.50      0   

      gender_Female  gender_Male  Partner_No  Partner_Yes  Dependents_No  ...  \
0                 1            0           0            1              1  ...   
1                 0            1           1            0              1  ...   
2                 0            1           1            0              1  ...   
3                 0            1           1            0              1  ...   
4                 1            0           1            0              1  ...   
...             ...          ...         ...          ...            ...  ...   
7027              0            1           0            1              0  ...   
7028              1            0           0            1              0  ...   
7029              1            0           0            1              0  ...   
7030              0            1           0            1              1  ...   
7031              0            1           1            0              1  ...   

      PaymentMethod_Bank transfer (automatic)  \
0                                           0   
1                                           0   
2                                           0   
3                                           1   
4                                           0   
...                                       ...   
7027                                        0   
7028                                        0   
7029                                        0   
7030                                        0   
7031                                        1   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                         0                               1   
1                                         0                               0   
2                                         0                               0   
3                                         0                               0   
4                                         0                               1   
...                                     ...                             ...   
7027                                      0                               0   
7028                                      1                               0   
7029                                      0                               1   
7030                                      0                               0   
7031                                      0                               0   

      PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24  \
0                              0                    1                     0   
1                              1                    0                     0   
2                              1                    1                     0   
3                              0                    0                     0   
4                              0                    1                     0   
...                          ...                  ...                   ...   
7027                           1                    0                     1  

In [4]:
base_dfz.columns

Index(['Unnamed: 0', 'SeniorCitizen', 'MonthlyCharges', 'TotalCharges',
       'Churn', 'gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract

In [6]:
base_dfz.TotalCharges = pd.to_numeric(base_dfz.TotalCharges, errors='coerce')
base_dfz.isnull().sum()

Unnamed: 0                                 0
SeniorCitizen                              0
MonthlyCharges                             0
TotalCharges                               0
Churn                                      0
gender_Female                              0
gender_Male                                0
Partner_No                                 0
Partner_Yes                                0
Dependents_No                              0
Dependents_Yes                             0
PhoneService_No                            0
PhoneService_Yes                           0
MultipleLines_No                           0
MultipleLines_No phone service             0
MultipleLines_Yes                          0
InternetService_DSL                        0
InternetService_Fiber optic                0
InternetService_No                         0
OnlineSecurity_No                          0
OnlineSecurity_No internet service         0
OnlineSecurity_Yes                         0
OnlineBack

In [8]:
base_dfz.dropna(how = 'any', inplace = True)

In [9]:
base_dfz.shape

(7032, 52)

In [10]:
base_dfz=base_dfz.drop('Unnamed: 0',axis=1)

In [12]:
x=base_dfz.drop('Churn',axis=1)
x.shape

(7032, 50)

In [14]:
y=base_dfz['Churn']
y.shape

(7032,)

In [15]:
#train Test Split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [16]:
x_train.shape

(5625, 50)

In [17]:
x_test.shape

(1407, 50)

## Decision Tree Classifier

In [18]:
model_dt=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [19]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [20]:
y_pred=model_dt.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
model_dt.score(x_test,y_test)

0.7938877043354655

In [22]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.84      0.89      0.87      1053
           1       0.61      0.51      0.56       354

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.79      1407



In [23]:
sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(x,y)

In [24]:
xr_train,xr_test,yr_train,yr_test=train_test_split(X_resampled, y_resampled,test_size=0.2)

In [26]:
model_dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [27]:
model_dt_smote.fit(xr_train,yr_train)
yr_predict = model_dt_smote.predict(xr_test)
model_score_r = model_dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

0.9452054794520548
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       524
           1       0.94      0.96      0.95       644

    accuracy                           0.95      1168
   macro avg       0.95      0.94      0.94      1168
weighted avg       0.95      0.95      0.95      1168



In [28]:
print(metrics.confusion_matrix(yr_test, yr_predict))

[[487  37]
 [ 27 617]]


## Random Forest Classifier

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
model_rf=RandomForestClassifier(n_estimators=100, criterion='entropy', random_state = 100,max_depth=6, min_samples_leaf=8)


In [31]:
model_rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=6, min_samples_leaf=8,
                       random_state=100)

In [32]:
y_pred=model_rf.predict(x_test)

In [33]:
model_rf.score(x_test,y_test)

0.8017057569296375

In [34]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.84      0.92      0.87      1053
           1       0.65      0.46      0.54       354

    accuracy                           0.80      1407
   macro avg       0.74      0.69      0.71      1407
weighted avg       0.79      0.80      0.79      1407



In [35]:
 sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(x,y)

In [36]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

In [37]:
model_rf_smote=RandomForestClassifier(n_estimators=100, criterion='entropy', random_state = 100,max_depth=6, min_samples_leaf=8)


In [38]:
model_rf_smote.fit(xr_train1,yr_train1)

RandomForestClassifier(criterion='entropy', max_depth=6, min_samples_leaf=8,
                       random_state=100)

In [40]:
yr_predict1 = model_rf_smote.predict(xr_test1)

In [41]:
model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)

In [42]:
accuracy = model_rf_smote.score(xr_train1, yr_train1)
print("Best Model Training Score: {:.4f}".format(accuracy))

accuracy = model_rf_smote.score(xr_test1, yr_test1)
print("Best Model Testing Score: {:.4f}".format(accuracy))

Best Model Training Score: 0.9398
Best Model Testing Score: 0.9490


In [43]:
# print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

              precision    recall  f1-score   support

           0       0.96      0.92      0.94       520
           1       0.94      0.97      0.96       656

    accuracy                           0.95      1176
   macro avg       0.95      0.95      0.95      1176
weighted avg       0.95      0.95      0.95      1176



In [44]:
print(metrics.confusion_matrix(yr_test1, yr_predict1))

[[479  41]
 [ 19 637]]


In [45]:
yr_predict1= model_rf_smote.predict(x)

In [46]:
#Making predictions
pred_rf1 = model_rf_smote.predict(x)
pred_prob_rf1 = model_rf_smote.predict_proba(x)

pred_rf1

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [47]:
# probabilities
pred_prob_rf1

array([[0.21717689, 0.78282311],
       [0.88838837, 0.11161163],
       [0.29613559, 0.70386441],
       ...,
       [0.44618612, 0.55381388],
       [0.04225161, 0.95774839],
       [0.77539982, 0.22460018]])

In [48]:
pred_prob_rf1.shape

(7032, 2)

In [49]:
accuracy = model_rf_smote.score(xr_train1, yr_train1)
print("Best Model Training Score: {:.4f}".format(accuracy))
#print("Best Model Training Accuracy: {:.4f}".format(accuracy[1]))

accuracy = model_rf_smote.score(xr_test1, yr_test1)
print("Best Model Testing Score: {:.4f}".format(accuracy))
#print("Best Model Testing Accuracy: {:.4f}".format(accuracy[1]))

Best Model Training Score: 0.9398
Best Model Testing Score: 0.9490


In [50]:
# function to select second column for probabilities
def column(matrix, i):
    return [row[i] for row in matrix]

column(pred_prob_rf1, 1)

[0.7828231065755847,
 0.11161162856928648,
 0.703864405543361,
 0.08173075564810818,
 0.9755324367206665,
 0.9696889208519984,
 0.7874339216975743,
 0.6269279971945776,
 0.7651260547090095,
 0.05895426157638323,
 0.4248816786984589,
 0.015857008786336422,
 0.3920344840413577,
 0.6405608258479408,
 0.6909010376056365,
 0.04495274485997504,
 0.0252009397989849,
 0.1631019493260997,
 0.6173285473490033,
 0.8021363278017813,
 0.8886210336611543,
 0.06514598845408448,
 0.6068553461154689,
 0.06664507815000535,
 0.20131623428666695,
 0.25508409826574474,
 0.6922096257677889,
 0.7160022406997275,
 0.01710102838097753,
 0.6070969606842286,
 0.10000646663712706,
 0.9501631471728167,
 0.07748604487988052,
 0.4884227556790189,
 0.862590813584721,
 0.08514505964345216,
 0.9565657230907632,
 0.7361060660669545,
 0.7916036382554259,
 0.9433310543150829,
 0.35927635543927144,
 0.024070824247187407,
 0.01449315197948855,
 0.021327700639852766,
 0.4623229771992512,
 0.7077596533503581,
 0.8625939544272

In [ ]:
# 9.4. Joining the raw data witht the predictions

# output = base_df.copy()
# output['Predictions - Churn or Not'] = pred_rf1
# output['Predictions - Probability to Churn'] = column(pred_prob_rf1, 1)
# output['Predictions - Churn or Not Desc'] = 'Empty'
# output['Predictions - Churn or Not Desc'][output['Predictions - Churn or Not'] == 0] = 'Retention'
# output['Predictions - Churn or Not Desc'][output['Predictions - Churn or Not'] == 1] = 'Churn'
# output

In [ ]:
# output['new'] = output['Predictions - Churn or Not'][(output['Predictions - Churn or Not'] == output.Churn.map(dict('Yes'=1, 'No'=0)))]
# output

In [ ]:
# output['new'].isna().sum()

In [ ]:
# output.drop('new', axis=1)

In [ ]:
# output.to_csv('Churn Predictions Output_rf.csv', sep='\t')

In [ ]:
# import pickle

In [ ]:
# filename = 'model.sav'

In [ ]:
# filename = 'model_1.pkl'

In [ ]:
# pickle.dump(model_rf_smote, open(filename, 'wb'))

In [ ]:
# output.to_csv('output.csv')

In [ ]:
# load_model = pickle.load(open(filename, 'rb'))

In [ ]:
# model_score_r1 = load_model.score(xr_test1, yr_test1)

In [ ]:
# model_score_r1